---

- hosts: [g1]
  become: true

  tasks:
    - ping:

    - name: Update apt repo and cache
      become: true
      apt: 
        upgrade: yes

    - name: Install Apache
      become: true
      apt:
        name: apache2
        update_cache: yes

    - name: Install Python3
      apt:
        name: python3

    - name: Install Pip3
      apt:
        name: python3-pip

    - name: Install Mod_Wsgi
      apt:
        name: libapache2-mod-wsgi-py3

    - name: Install flask
      pip:
        name: flask
        
    - name: Delete content & directory
      file:
        state: absent
        path: /var/www/flask_app

    - name: Create Flask app directory
      become: true
      file:
         path: /var/www/flask_app
         state: directory
         owner: ubuntu
         mode: 0777
        
    - name: copy ssh private-key
      copy: 
         src: ~/.ssh/id_rsa
         dest: /root/.ssh/id_rsa.github
         owner: root
         group: root
         mode: 0600
         
    - name: Make directory git safe
      shell: "git config --global --add safe.directory /var/www/flask_app"

    - name: Clone Flask app
      become: true
      become_user: ubuntu
      git:
        repo: git@github.com:deecodz/flask-assignment.git
        key_file: /root/.ssh/id_rsa.github
        dest: /var/www/flask_app
        clone: yes
        #version: main
        #update: yes
        accept_hostkey: yes

    - name: Configure mod_wsgi
      become: yes
      template:
        src: /var/www/flask_app/flask_app.conf
        dest: /etc/apache2/sites-available/flask_app.conf
        

    - name: Enable Flask app virtual host
      become: yes
      file:
        src: /etc/apache2/sites-available/flask_app.conf
        dest: /etc/apache2/sites-enabled/flask_app.conf
        state: link

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ flask_app.conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Restart Apache service
      become: yes
      service:
        name: apache2
        state: restarted
