---

- hosts: [g1]
  become: yes
  become_user: ubuntu
  gather_facts: false

  tasks:
    - ping:

    - name: Update apt repo and cache
      become: yes
      apt: 
        update_cache: yes 
        force_apt_get: yes 
        cache_valid_time=3600

   - name: Install Apache
     become: yes
     apt:
       name: apache2

    - name: Install Python3
      apt:
        name: python3

    - name: Install Pip3
      apt:
        name: python3-pip

    - name: Install Mod_Wsgi
      apt:
        name: libapache2-mod-wsgi-py3

    - name: Install flask
      pip:
        name: flask

    - name: Create Flask app directory
      become: yes
      file:
        path: /var/www/flask_app
        state: directory
        mode: 755

    - name: Clone Flask app
      git:
        repo: git@github.com:deecodz/flask-assignment.git
        dest: /var/www/flask_app
        clone: yes
        version: main
        update: yes

    - name: Configure mod_wsgi
      become: yes
      template:
        src: /var/www/flask_app/flask-assignment/flask_app.conf
        dest: /etc/apache2/sites-available/flask_app.conf
        

    - name: Enable Flask app virtual host
      become: yes
      file:
        src: /etc/apache2/sites-available/flask_app.conf
        dest: /etc/apache2/sites-enabled/flask_app.conf
        state: link

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ flask_app.conf }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Restart Apache service
      become: yes
      service:
        name: apache2
        state: restarted






